name: presentation
description: Flutter App | Presentaion Layer.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../data

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

dev_dependencies:
  build_runner: ^2.1.7
  injectable_generator: ^1.5.3